version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: city_explorer
      MYSQL_USER: root
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"

  spring-app:
    build:
      context: ./city_explorer_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/city_explorer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin

  spring-app-angular:
    build:
      context: ./city_explorer_angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-app