version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: city_explorer
    ports:
      - "3306:3306"

  app-back:
    build:
      context: ./city_explorer_back
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/city_explorer?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

  app-front:
    build:
      context: ./city_explorer_angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - app-back